const typesData = [
  {
    type: 'uber_x',
    name: 'TaxiX',
    numberOfPassenger: 3,
    baseFare: 1.56,
    minimumFare: 4.18,
    costPerKm: 0.89,
    costPerMin: 0.24,
    averageSpeedPerMin: 0.75,
    description: 'Affordable rides all to yourself',
  },
  {
    type: 'comfort',
    name: 'Comfort',
    numberOfPassenger: 3,
    baseFare: 1.76,
    minimumFare: 4.48,
    costPerKm: 0.99,
    costPerMin: 0.34,
    averageSpeedPerMin: 0.83,
    description: 'Newer cars with extra legroom',
  },
  {
    type: 'uber_xl',
    name: 'TaxiXL',
    numberOfPassenger: 5,
    baseFare: 1.96,
    minimumFare: 4.98,
    costPerKm: 1.29,
    costPerMin: 0.44,
    averageSpeedPerMin: 0.66,
    description: 'Affordable rides for group up to 6',
  },
];
